import os
from pathlib import Path

APP_NAME = "QuantumHub"
APP_VERSION = "0.3.0"

# Database
DATA_DIR = Path(os.path.expanduser("~/.local/share/quantumhub"))
DB_PATH = DATA_DIR / "quantumhub.db"

# Docker
LOCAL_DOCKER_SOCKET = "unix:///var/run/docker.sock"
DEFAULT_DOCKER_API_VERSION = "auto"

# Polling intervals (ms)
CONTAINER_POLL_INTERVAL_MS = 3000
STATS_POLL_INTERVAL_MS = 2000
IMAGE_POLL_INTERVAL_MS = 10000

# System polling intervals (ms)
DASHBOARD_POLL_INTERVAL_MS = 5000
PROCESS_POLL_INTERVAL_MS = 5000
APP_POLL_INTERVAL_MS = 5000
SERVICE_POLL_INTERVAL_MS = 10000

# SSH defaults
DEFAULT_SSH_PORT = 22
TUNNEL_LOCAL_BIND_HOST = "127.0.0.1"

# Settings defaults
SETTINGS_VIEW_INDEX = 10
PACKAGES_VIEW_INDEX = 11
HOSTS_VIEW_INDEX = 12
NETWORK_VIEW_INDEX = 13
APT_REPOS_VIEW_INDEX = 14
STARTUP_VIEW_INDEX = 15
FIREWALL_VIEW_INDEX = 16
NETWORK_TOOLS_VIEW_INDEX = 17
FILE_TRANSFER_VIEW_INDEX = 18
VM_VIEW_INDEX = 19
GUIDE_VIEW_INDEX = 20
JOURNAL_VIEW_INDEX = 21
CRON_VIEW_INDEX = 22
USERS_VIEW_INDEX = 23
DISK_USAGE_VIEW_INDEX = 24
REGISTRY_VIEW_INDEX = 25
DEFAULT_TERMINAL_FONT_SIZE = 12
DEFAULT_CONFIRM_BEFORE_KILL = True
DEFAULT_AUTO_CONNECT_LAST = False
DEFAULT_SSH_AUTH_METHOD = "key"
DEFAULT_POLL_MULTIPLIER = 1.0
